repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2.20.0
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
        exclude: bibtex.bib
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: v22.3.0
    hooks:
    -   id: black
